coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default:
        target: 5%
        threshold: 1%
        only_pulls: false
      backend:
        paths:
          - backend/src/
        target: 30%
        threshold: 5%
        only_pulls: false

    patch:
      default:
        target: 30%
        threshold: 5%

parsers:
  java:
    enable: 100

comment:
  layout: "header, diff, changes, files"
  require_changes: false