name: Security Scan
<<<<<<< HEAD
=======

>>>>>>> 86e3fceec70a6aaaaebb89626c2f534e6cb2fc03
on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
<<<<<<< HEAD
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
      - uses: gitleaks/gitleaks-action@v2
>>>>>>> 86e3fceec70a6aaaaebb89626c2f534e6cb2fc03
